import { resolve, relative, dirname } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { sync as globSync } from 'glob';
import * as clack from '@clack/prompts';

interface Opts {
  flags: Record<string, string | boolean>;
}

/**
 * Default patterns mirror the Xenosis filename convention. Override with
 * `--patterns "src/repository/*.repository.ts,src/services/*.service.ts"`.
 * Both .ts and .js are matched so the same command works in either project.
 */
const DEFAULT_PATTERNS = [
  'src/repository/*.repository.{ts,js}',
  'src/services/*.service.{ts,js}',
  'src/api/**/*.controller.{ts,js}',
  'src/jobs/*.job.{ts,js}',
  'src/middlewares/*.middleware.{ts,js}',
];

export async function runGenerateManifest({ flags }: Opts): Promise<void> {
  clack.intro('Generate Xenosis autoload manifest');

  const patterns =
    typeof flags.patterns === 'string'
      ? flags.patterns.split(',').map((s) => s.trim()).filter(Boolean)
      : DEFAULT_PATTERNS;

  const cwd = process.cwd();
  const matched = patterns
    .flatMap((p) => globSync(p, { cwd, absolute: false }))
    .filter((p, i, arr) => arr.indexOf(p) === i)
    .sort();

  if (matched.length === 0) {
    clack.cancel(
      `No files matched ${patterns.length} pattern(s) under ${cwd}. ` +
        'Pass --patterns "<glob1>,<glob2>" or run from the service directory.',
    );
    process.exit(1);
  }

  const outPath = resolve(cwd, 'src/.xenosis-manifest.ts');

  // Build the manifest source. Each entry is a static `() => import('./...')`
  // so a bundler can statically analyse the imports — the runtime hook in
  // @xenosisorg/xenosis-core's autoload loader awaits these to retrieve the module.
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by `xenosis generate manifest`. Do not edit.');
  lines.push('// Re-run after adding/removing autoloaded files.');
  lines.push('');
  lines.push('export const __xenosisManifest: Record<string, () => Promise<unknown>> = {');

  const manifestDir = dirname(outPath);
  for (const file of matched) {
    // Compute the import specifier relative to src/.xenosis-manifest.ts.
    const absFile = resolve(cwd, file);
    let spec = relative(manifestDir, absFile).replace(/\\/g, '/');
    if (!spec.startsWith('.')) spec = `./${spec}`;
    // Strip the .ts/.js suffix so TS resolves the source file; if the user
    // bundles to .js the bundler resolves the same way.
    spec = spec.replace(/\.(ts|js|mjs|cjs)$/i, '');
    lines.push(`  '${file}': () => import('${spec}'),`);
  }
  lines.push('};');
  lines.push('');

  const s = clack.spinner();
  s.start(`Writing manifest with ${matched.length} entries`);
  await writeFile(outPath, lines.join('\n'), 'utf-8');
  s.stop(`Wrote src/.xenosis-manifest.ts (${matched.length} entries)`);

  clack.outro(
    [
      `🎉 Manifest generated.`,
      ``,
      `  Bundle your service:`,
      `    pnpm exec tsup src/service.ts --format esm`,
      ``,
      `  The runtime detects src/.xenosis-manifest.ts automatically and`,
      `  uses it instead of the runtime glob — so a bundled service can`,
      `  resolve every autoloaded module statically.`,
      ``,
      `  Re-run "xenosis generate manifest" whenever you add or remove`,
      `  files that match the autoload patterns.`,
    ].join('\n'),
  );
}
