import { resolve, relative, dirname } from 'node:path';
import { writeFile } from 'node:fs/promises';
import { sync as globSync } from 'glob';
import * as clack from '@clack/prompts';

interface Opts {
  flags: Record<string, string | boolean>;
}

/**
 * Default patterns mirror the Xenosis filename convention. Override with
 * `--patterns "src/repository/*.repository.ts,src/services/*.service.ts"`.
 * Both .ts and .js are matched so the same command works in either project.
 */
export const DEFAULT_PATTERNS = [
  'src/repository/*.repository.{ts,js}',
  'src/services/*.service.{ts,js}',
  'src/api/**/*.controller.{ts,js}',
  'src/jobs/*.job.{ts,js}',
  'src/middlewares/*.middleware.{ts,js}',
];

/**
 * Write `src/.xenosis-manifest.ts` for the service at `cwd`. Shared by
 * `generate manifest` and `build`. Returns the number of entries, or null when
 * nothing matched.
 */
export async function writeManifest(
  cwd: string,
  patterns: string[] = DEFAULT_PATTERNS,
): Promise<number | null> {
  const matched = patterns
    .flatMap((p) => globSync(p, { cwd, absolute: false }))
    .filter((p, i, arr) => arr.indexOf(p) === i)
    .sort();

  if (matched.length === 0) return null;

  const outPath = resolve(cwd, 'src/.xenosis-manifest.ts');
  const manifestDir = dirname(outPath);
  const lines: string[] = [
    '// AUTO-GENERATED by `xenosis generate manifest` / `xenosis build`. Do not edit.',
    '// Re-run after adding/removing autoloaded files.',
    '',
    'export const __xenosisManifest: Record<string, () => Promise<unknown>> = {',
  ];
  for (const file of matched) {
    const absFile = resolve(cwd, file);
    let spec = relative(manifestDir, absFile).replace(/\\/g, '/');
    if (!spec.startsWith('.')) spec = `./${spec}`;
    spec = spec.replace(/\.(ts|js|mjs|cjs)$/i, '');
    lines.push(`  '${file}': () => import('${spec}'),`);
  }
  lines.push('};', '');
  await writeFile(outPath, lines.join('\n'), 'utf-8');
  return matched.length;
}

export async function runGenerateManifest({ flags }: Opts): Promise<void> {
  clack.intro('Generate Xenosis autoload manifest');

  const patterns =
    typeof flags.patterns === 'string'
      ? flags.patterns.split(',').map((s) => s.trim()).filter(Boolean)
      : DEFAULT_PATTERNS;

  const cwd = process.cwd();
  const s = clack.spinner();
  s.start('Writing manifest');
  const count = await writeManifest(cwd, patterns);
  if (count === null) {
    s.stop('No files matched');
    clack.cancel(
      `No files matched ${patterns.length} pattern(s) under ${cwd}. ` +
        'Pass --patterns "<glob1>,<glob2>" or run from the service directory.',
    );
    process.exit(1);
  }
  s.stop(`Wrote src/.xenosis-manifest.ts (${count} entries)`);

  clack.outro(
    [
      `🎉 Manifest generated.`,
      ``,
      `  Bundle your service:`,
      `    pnpm exec tsup src/service.ts --format esm`,
      ``,
      `  The runtime detects src/.xenosis-manifest.ts automatically and`,
      `  uses it instead of the runtime glob — so a bundled service can`,
      `  resolve every autoloaded module statically.`,
      ``,
      `  Re-run "xenosis generate manifest" whenever you add or remove`,
      `  files that match the autoload patterns.`,
    ].join('\n'),
  );
}
