import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import request from 'supertest';
import type { TestContainer } from '@xenosisorg/xenosis-testing';
import { setupTestApp } from './setup';

/**
 * Generated by 'xenosis dev' Time-Travel Replay (Promote to test).
 * Source trace: 45f3a48c-d97d-47c4-9367-509e81822830
 * Captured: orders → cart.getCart
 *           GET /api/v1/carts/user-42
 *           18ms · ok
 *
 * Review the assertion before keeping — the recorded response was a
 * snapshot of one moment, not necessarily the canonical contract.
 */
describe('replayed: getCart', () => {
  let ctx: TestContainer;

  beforeAll(async () => { ctx = await setupTestApp(); });
  afterAll(async () => { await ctx.cleanup(); });

  it('GET /api/v1/carts/user-42 reproduces the recorded response', async () => {
    const recorded = {
  "userId": "user-42",
  "lines": [
    {
      "sku": "SKU-TEE",
      "name": "Xenosis T-shirt",
      "qty": 2,
      "unitPrice": 25
    },
    {
      "sku": "SKU-MUG",
      "name": "Xenosis Mug",
      "qty": 1,
      "unitPrice": 12
    }
  ]
};
    const res = await request(ctx.server)
      .get('/api/v1/carts/user-42')
      .expect(200);
    expect(res.body).toEqual(recorded);
  });
});
