// Generated by `prisma generate` into ../generated/client. Each Prisma
// schema in the workspace must declare a unique `output` path so the
// shared @prisma/client package doesn't get overwritten when the next
// package regenerates.
import { PrismaClient } from '../generated/client/index.js';

export { PrismaClient };

/**
 * @typedef {import('@xenosisorg/xenosis-core').SchemaPackage<PrismaClient>} SchemaPackage
 */

/**
 * Shared events schema (JavaScript variant). A service binds it through
 * xenosis.config.json:
 *
 *   "schemas": {
 *     "eventsDb": { "package": "@example/psql-events-js", "connector": "psqlEvents" }
 *   }
 *
 * @xenosisorg/xenosis-core calls `createClient(connector)` and registers the resulting
 * PrismaClient under `cradle.eventsDb` for the consuming service.
 */

/** @type {SchemaPackage} */
const pkg = {
  createClient(connector) {
    const url =
      connector.url ??
      `postgresql://${connector.username}:${connector.password}@${connector.host}:${connector.port}/${connector.database}`;

    return new PrismaClient({
      datasources: { db: { url } },
    });
  },

  async disconnect(client) {
    await client.$disconnect();
  },

  schema: {
    type: 'prisma',
    schemaPath: new URL('../prisma/schema.prisma', import.meta.url).pathname,
    migrationsPath: new URL('../prisma/migrations', import.meta.url).pathname,
  },
};

export default pkg;
export const { createClient, schema, disconnect } = pkg;
