// Generated by `prisma generate` into ../generated/client (configured via
// the `output` field in prisma/schema.prisma). Using a custom output keeps
// this package's client isolated so a sibling Prisma schema (e.g. the JS
// example in examples/js/db-schemas/psql-events-js) doesn't overwrite it.
import { PrismaClient } from '../generated/client/index.js';
import type { SchemaPackage } from '@xenosisorg/xenosis-core';

export { PrismaClient };

const pkg: SchemaPackage<PrismaClient> = {
  createClient(connector) {
    const url =
      connector.url ??
      `postgresql://${connector.username}:${connector.password}@${connector.host}:${connector.port}/${connector.database}`;

    return new PrismaClient({
      datasources: { db: { url } },
    });
  },

  async disconnect(client) {
    await client.$disconnect();
  },

  schema: {
    type: 'prisma',
    schemaPath: new URL('../prisma/schema.prisma', import.meta.url).pathname,
    migrationsPath: new URL('../prisma/migrations', import.meta.url).pathname,
  },
};

export default pkg;
export const { createClient, schema, disconnect } = pkg;
