// Generated by `prisma generate` into ../generated/client (configured via
// the `output` field in prisma/schema.prisma). Using a custom output keeps
// this package's client isolated so a sibling Prisma schema (e.g. the JS
// example in examples/js/db-schemas/psql-events-js) doesn't overwrite it.
import { PrismaClient } from '../generated/client/index.js';
import type { SchemaPackage } from '@xenosisorg/xenosis-core';

export { PrismaClient };

const pkg: SchemaPackage<PrismaClient> = {
  createClient(connector) {
    const url =
      connector.url ??
      `postgresql://${connector.username}:${connector.password}@${connector.host}:${connector.port}/${connector.database}`;

    return new PrismaClient({
      datasources: { db: { url } },
    });
  },

  // Used by @xenosisorg/xenosis-testing. The testing kit boots a PGlite instance and
  // replays this package's migrations (from schema.migrationsPath) onto it,
  // then hands the live instance here. We just wrap it in the Prisma driver
  // adapter — the package owns the client, the testing kit owns the engine.
  async createTestClient(handle) {
    const { PrismaPGlite } = await import('pglite-prisma-adapter');
    // Cast at the boundary: pglite-prisma-adapter@0.6 bundles its own copy of
    // @prisma/driver-adapter-utils, whose SqlDriverAdapter type is structurally
    // identical but nominally distinct from the one our @prisma/client expects.
    // They're runtime-compatible (same Prisma 6 line).
    const adapter = new PrismaPGlite(handle as never) as never;
    return new PrismaClient({ adapter });
  },

  async disconnect(client) {
    await client.$disconnect();
  },

  schema: {
    type: 'prisma',
    schemaPath: new URL('../prisma/schema.prisma', import.meta.url).pathname,
    migrationsPath: new URL('../prisma/migrations', import.meta.url).pathname,
  },
};

export default pkg;
export const { createClient, createTestClient, schema, disconnect } = pkg;
